shutdown;
------------------------------------------
---------HSQL 스키마 생성 및 권한---------------
------------------------------------------
--------- 멤버 테이블
create sequence seq
start with 1000;

DROP SEQUENCE seq;
drop table member;

create table member(
	userid varchar(20), -- 아이디
	password varchar(20),  -- 비번
	name varchar(20), -- 이름
	phone varchar(20), -- 전화번호
	addr varchar(50), -- 주소
	birth varchar(20), -- 생년
	que varchar(30), -- 비번찾기 질문
	ans varchar(30), -- 비번찾기 대답
	constraint member_pk primary key (userid)
);

insert into member values(
	'hong','1','홍길동','01022223333','서울','20000101','첫강아지','망고'
);
insert into member values(
	'kim','1','김유신','01044445555','강원','19900101','첫강아지','멍멍이'
);
insert into member values(
	'lee','1','이순신','01066667777','충남','19950101','첫강아지','진도'
);
select * from member;
-------- 푸드 카테고리 테이블

drop table food_cate;

create table food_cate(
	food_cate_seq int  generated by default as sequence seq,
	cate_name varchar(20),  -- 카테고리 이름
	constraint food_cate_pk2 primary key (food_cate_seq)
);
--시퀀스 1
insert into food_cate(food_cate_seq, cate_name) 
values(next value for seq, '보쌈'); 
--시퀀스 1
insert into food_cate(seq, cate_name) 
values(next value for seq, '중식'); 

select * from food_cate;

-------- 식당 테이블

drop table store;

create table store(
	store_seq int 
		generated by default as sequence seq,
	biz_name varchar(30) not null,
	food_cate_seq int not null,
	constraint store_pk primary key (store_seq),
	constraint store_food_cate_fk 
	foreign key (food_cate_seq)
		references food_cate(food_cate_seq)
);

insert into store(store_seq, biz_name, food_cate_seq ) 
values(next value for seq, '족발집(테스트)', '1');

select * from store;
select * from store where food_cate_seq = '1';
----------------------------------------------
-- 메뉴 테이블 
drop table menu cascade;

create table menu(
	menu_seq int  -- 메뉴 시퀀스
		generated by default as sequence seq, 
	food_name varchar(20) not null, -- 메뉴 이름
	image varchar(50),  -- 메뉴 이미지
	constraint menu_pk primary key (menu_seq)
);
-- 시퀀스 2
insert into menu(menu_seq, food_name, image ) 
values(next value for seq, '떡볶이', 'menu_ddokbokki.png'); 
-- 시퀀스 3
insert into menu(menu_seq, food_name, image ) 
values(next value for seq, '카르보나', 'menu_karbonara.png');
-- 시퀀스 4
insert into menu(menu_seq, food_name, image ) 
values(next value for seq, '순대', 'menu_soondae.png');
-- 시퀀스 5
insert into menu(menu_seq, food_name, image ) 
values(next value for seq, '돈까스', 'menu_dongas.png');
-- 시퀀스 6
insert into menu(menu_seq, food_name, image ) 
values(next value for seq, '김치볶음밥', 'menu_kimchibok.png');
-- 시퀀스 7
insert into menu(menu_seq, food_name, image ) 
values(next value for seq, '닭발', 'menu_dakbal.png');
-- 시퀀스 8
insert into menu(menu_seq, food_name, image ) 
values(next value for seq, '김밥', 'menu_kimbab.png');
-- 시퀀스 9
insert into menu(menu_seq, food_name, image ) 
values(next value for seq, '라면', 'menu_ramen.png');

select * from menu;
-----------------------------------------
-- 메뉴 및 가격 테이블(4페이지)
drop table store_menu;

create table store_menu(
	store_menu_seq int  -- 가게별 메뉴 시퀀스 (PK)
		generated by default as sequence seq,
	store_seq int not null, -- 가게 시퀀스 (FK)
	menu_seq int not null, -- 메뉴 시퀀스 (FK)
	price int not null,    -- 가격 
	constraint store_menu_pk primary key (store_menu_seq),
	constraint store_menu_store_fk 
		foreign key (store_seq)
		references store(store_seq),
	constraint store_menu_menu_fk 
		foreign key (menu_seq)
		references menu(menu_seq)
);



insert into store_menu(store_menu_seq, store_seq, menu_seq, price)
values(next value for seq,'9', '7', '15000');

--insert into store(store_seq, biz_name, food_cate_seq ) 
--values(store_seq.nextval, '고봉민김밥', '4');


select * from store_menu;



