shutdown;
--------------------------------------------
---------HSQL 스키마 생성 및 권한---------------

----------------------------------------------
--------- 멤버 테이블(1페이지)
drop table member;

create table member(
userid varchar(20),
password varchar(20), 
name varchar(20),
phone varchar(20),
addr varchar(50),
birth varchar(20),
que varchar(30),
ans varchar(30),
constraint member_pk primary key (userid)
);

-- alter table member
-- add constraint member_pk primary key(userid);

---------------------------------------------
-------- 푸드 카테고리 테이블(2페이지)
create sequence food_cate_seq
start with 1;

drop table food_cate;

create table food_cate(
	food_cate_seq int generated by default as sequence food_cate_seq,
	cate_name varchar(20),
constraint food_cate_pk primary key (food_cate_seq)
);

insert into food_cate(food_cate_seq, cate_name) 
values(next value for food_cate_seq, '보쌈족발');

-------------------------------------------
-- 식당 테이블(3페이지)
create sequence store_seq
start with 1;

drop table store;

create table store(
	store_seq int generated by default as sequence store_seq,
	biz_name varchar(30) not null,
	food_cate_seq int not null,
	constraint store_pk primary key (store_seq),
	constraint store_food_cate_fk 
	foreign key (food_cate_seq)
		references food_cate(food_cate_seq)
);

insert into store(store_seq, biz_name, food_cate_seq ) 
values(next value for store_seq, '족발집(테스트)', '1');

select * from store;
----------------------------------------------
-- 메뉴 테이블
create sequence menu_seq
start with 1;

drop table menu cascade;

create table menu(
menu_seq int generated by default as sequence menu_seq,
food_name varchar(20) not null,
profile varchar(20),
constraint menu_pk primary key (menu_seq)
);

insert into menu(menu_seq, food_name, profile ) 
values(next value for menu_seq, '닭발', 'default.png');

-----------------------------------------
-- 메뉴 및 가격 테이블(4페이지)
create sequence store_menu_seq
start with 1;

drop table store_menu;

create table store_menu(
	store_menu_seq int generated by default as sequence store_menu_seq,
	store_seq int not null,
	menu_seq int not null,
	price int not null,
	constraint store_menu_pk primary key (store_menu_seq),
	constraint store_menu_store_fk 
		foreign key (store_seq)
		references store(store_seq),
	constraint store_menu_menu_fk 
		foreign key (menu_seq)
		references menu(menu_seq)
);


--select * from store_menu where store_seq = 9;

--insert into store_menu(store_menu_seq, store_seq, menu_seq, price)
--values(store_menu_seq.nextval,'9', '7', '15000');

--insert into store(store_seq, biz_name, food_cate_seq ) 
--values(store_seq.nextval, '고봉민김밥', '4');





